routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Authentication
Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [\App\Http\Controllers\Auth\LoginController::class, 'login']);
Route::get('/logout', [\App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['middleware' => ['auth']], function () {

    Route::group(['prefix' => 'admin'], function () {
        Voyager::routes();
    });

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::group(['prefix' => 'udp'], function () {
        Route::group(['prefix' => 'administration'], function () {
            Route::group(['prefix' => 'request'], function () {
                Route::get('/getRequest', [\App\Http\Controllers\RequestUserController::class, 'getRequest']);
                Route::post('/store', [\App\Http\Controllers\RequestUserController::class, 'store']);
                Route::post('/{requestUser}/update', [\App\Http\Controllers\RequestUserController::class, 'update']);
                Route::get('/generatePDF/{requestUser}', [\App\Http\Controllers\RequestUserController::class, 'generatePDF']);
            });

            Route::group(['prefix' => 'users'], function () {
                Route::get('/getUsers', [\App\Http\Controllers\UserController::class, 'getUsers']);
                Route::get('/getUsersList', [\App\Http\Controllers\UserController::class, 'getUsersList']);
                Route::post('/store', [\App\Http\Controllers\UserController::class, 'store']);
                Route::post('/{user}/update', [\App\Http\Controllers\UserController::class, 'update']);
                Route::post('/importUsers', [\App\Http\Controllers\UserController::class, 'import'])->name('users.import');
            });
        });

    });

    Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::get('/v/{any?}/{any1?}/{any2?}/{any3?}/{any4?}', function ($any = null, $any1 = null, $any2 = null, $any3 = null, $any4 = null) {
        return view('layouts.coreui');
    })->where('vue', '.*')->name('rutas.vue');
});

app/Models/RequestUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RequestUser extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'document_code',
        'document_label',
        'r_to_c',
        's_to_c',
        'o_to_c',
        'f_to_c',
        'r_to_u',
        's_to_u',
        'o_to_u',
        'f_to_u',
        'check_code',
        'check_label',
        'pass_code',
        'pass_label',
        'elaborate',
        'status'
    ];

    protected $appends = ['StatusLabel'];

    public function scopeSearch($query, $search_term)
    {
        if ($search_term != null)
            $query->where('id', 'like', '%' . $search_term . '%')
                ->where('created_at', 'like', '%' . $search_term . '%');
    }

    public function getStatusLabelAttribute()
    {
        switch ($this->status) {
            case 'in_review':
                return '<span class="badge badge-info full-20">
                            <strong>EN REVISIÓN</strong>
                        </span>';
            case 'approved':
                return '<span class="badge badge-success full-20">
                            <strong>APROBADO</strong>
                        </span>';
            case 'rejected':
                return '<span class="badge badge-danger full-20">
                            <strong>RECHAZADO</strong>
                        </span>';
            default:
                return '<span class="badge badge-danger full-20">
                            <strong>' . $this->status . '</strong>
                        </span>';
        }
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.coreui');
    }
}

resources/views/tasks/assignments/assigment.blade.php
<x-app-layout>
    <div class="card">
        <div class="card-header bg-espumados text-uppercase">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                    <nav aria-label="breadcrumb" role="navigation">
                        <ol class="breadcrumb m-0" style="border: none !important;">
                            <li class="breadcrumb-item">
                                <a class="text-gray-500">
                                    Gestión de tareas
                                </a>
                            </li>
                            <li class="breadcrumb-item active">
                                <a href="{{ route('tasks.assigment.index') }}">
                                    Asignación
                                </a>
                            </li>
                        </ol>
                    </nav>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
                    <button class="btn btn-info float-right"
                            id="refresh"
                            title="Refrescar manualmente los registros">
                        <i class="fas fa-sync"></i>
                    </button>
                </div>
            </div>
        </div>
        <div class="pl-4 pr-4 pt-4">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <!-- Button trigger modal -->
                    <div class="btn-group">
                        <button type="button"
                                class="btn btn-primary"
                                data-target="#createMassive"
                                data-backdrop="static"
                                data-toggle="modal"
                                data-keyboard="false">
                            <b style="font-size: 16px !important;">Carga masiva</b>
                        </button>
                        {{--                        <button type="button"--}}
                        {{--                                class="btn btn-outline-primary"--}}
                        {{--                                data-toggle="modal"--}}
                        {{--                                data-target="#machinery"
                        {{--                                data-backdrop="static">--}}
                        {{--                            Maquinaria--}}
                        {{--                        </button>--}}
                        <button type="button"
                                class="btn btn-secondary"
                                data-target="#createIndividual"
                                data-backdrop="static"
                                data-toggle="modal"
                                data-keyboard="false">
                            <b style="font-size: 16px !important;">Nueva tarea</b>
                        </button>
                    </div>
                </div>
                @include('tasks.assignments.create-massive')
                @include('tasks.assignments.create-individual')
                @include('tasks.assignments.machinery')
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <form class="form-inline my-2 my-lg-0 float-right">
                        <input class="form-control mr-sm-2" type="text" name="search-tasks"
                               value="{{request('search-tasks')}}" aria-label="Search">
                        <div class="btn-group">
                            <button class="btn btn-secondary my-2 my-sm-0"
                                    type="submit">
                                <b style="font-size: 16px !important;">Buscar</b>
                            </button>
                            <a href="{{route('tasks.assigment.index')}}"
                               class="btn btn-primary">
                                <b style="font-size: 16px !important;">Limpiar</b>
                            </a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="card-body" id="cardAssigment">
            <div class="table-responsive">
                <table id="assigmentTable" class="table table-bordered table-sm table-striped table-condensed">
                    <thead class="headerStatic">
                    <tr class="bg-orange">
                        <th class="tt-espumados">ID</th>
                        <th class="tt-espumados">N° Semi-Elaborado</th>
                        <th class="tt-espumados">N° Producto terminado</th>
                        <th class="tt-espumados">Nombre del cliente</th>
                        <th class="tt-espumados">Maquina</th>
                        <th class="tt-espumados">Material</th>
                        <th class="tt-espumados">Estado</th>
                        <th class="tt-espumados">Asiganación (Fecha y Hora)</th>
                        <th class="tt-espumados">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($assigmentTasks as $assigmentTask )
                        <tr>
                            <td class="text-center">{{ $assigmentTask->id }}</td>
                            <td class="text-center">{{ $assigmentTask->order_sem }}</td>
                            <td class="text-center">{{ $assigmentTask->order_pt }}</td>
                            <td class="text-uppercase">{{ $assigmentTask->client_name }}</td>
                            <td class="text-uppercase">{{ $assigmentTask->machinery->name }}</td>
                            <td class="text-uppercase">{{ $assigmentTask->material->name }}</td>
                            <td class="text-center">{!! $assigmentTask->status_label !!}</td>
                            <td class="text-center">{{ $assigmentTask->created_at->format('d-m-Y g:i a') }}</td>
                            <td class="text-center justify-content-center" width="120px">
                                <div class="btn-group">
                                    <a style="cursor: pointer"
                                       class="text-info"
                                       data-toggle="modal"
                                       data-backdrop="static"
                                       data-target="#detailTask-{{ $assigmentTask->id }}"
                                       title="Ver">
                                        <i class="fas fa-eye fa-2x"></i>
                                    </a>
                                    @include('tasks.assignments.detail-task')
                                    &nbsp;
                                    <a style="cursor: pointer"
                                       class="text-warning"
                                       data-toggle="modal"
                                       data-backdrop="static"
                                       data-target="#editTask-{{ $assigmentTask->id }}"
                                       title="Editar">
                                        <i class="fas fa-edit fa-2x"></i>
                                    </a>
                                    @include('tasks.assignments.edit-task')
                                </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <br>
                {{$assigmentTasks->appends(request()->all())->render()}}
            </div>
        </div>
    </div>
</x-app-layout>

<script>
    $('#refresh').click(function () {
        window.location.reload();
    });
</script>

resources/views/tasks/assignments/create-massive.blade.php
<!-- Modal -->
<div class="modal fade" id="createMassive" tabindex="-1" aria-labelledby="createMassiveLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title bg-espumados text-uppercase" id="createMassiveLabel">
                    Carga masiva de tareas
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{route('tasks.assigment.import')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="modal-body bv-modal">
                    <div class="row">
                        <div class="col-md-10 ml-auto mr-auto">
                            <blockquote class="blockquote">
                                Por favor seleccione el archivo a subir, tenga en cuenta que:
                                <strong>El archivo debe ser .XLSX</strong>
                                <br>
                            </blockquote>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="form-group">
                                <input type="file"
                                       class="form-control"
                                       name="file"
                                       style="height: 41px !important;"
                                       accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                                       required>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">
                            Cerrar
                        </button>
                        <button type="submit" class="btn btn-primary">
                            Cargar datos
                        </button>
                        <a href="{{ asset('documents/example-tasks.xlsx') }}"
                           download="archivo-de-ejemplo"
                           class="btn btn-success"
                           title="Descargar"
                           style="cursor: pointer !important; color: white !important;">
                            <img src="{{asset('assets/img/icons8-microsoft-excel-22.png')}}"
                                 width="18px"
                                 height="18px"
                                 style="display: inline !important;"
                                 alt="icons8-microsoft-excel-22.png">
                            Plantilla de ejemplo
                        </a>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/tasks/assignments/detail-task.blade.php
<!-- Modal -->
<div class="modal fade" id="detailTask-{{ $assigmentTask->id }}" tabindex="-1"
     aria-labelledby="detailTask-{{ $assigmentTask->id }}-Label" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title bg-espumados text-uppercase"
                    id="detailTask-{{ $assigmentTask->id }}-Label">
                    Detalle de la tarea #{{ $assigmentTask->id }}
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body bv-modal" style="text-align: left !important;">
                <div class="row">
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label for="order_sem" class="bg-espumados">
                                <h5>
                                    <b>
                                        N° Orden de Semi-Elaborados
                                    </b>
                                </h5>
                            </label>
                            <h5><b>{{ $assigmentTask->order_sem }}</b></h5>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label for="blq" class="bg-espumados">
                                <h5>
                                    <b>
                                        Bloque
                                    </b>
                                </h5>
                            </label>
                            <h5><b>{{ $assigmentTask->blq }}</b></h5>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label for="order_sem" class="bg-espumados">
                                <h5>
                                    <b>
                                        Cantidad por cortar
                                    </b>
                                </h5>
                            </label>
                            <h5><b>{{ $assigmentTask->quantity_pc }}</b></h5>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label for="material_id" class="bg-espumados">
                                <h5>
                                    <b>
                                        Material
                                    </b>
                                </h5>
                            </label>
                            <h5><b>{{ $assigmentTask->material->name }}</b></h5>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label for="machinery_id" class="bg-espumados">
                                <h5>
                                    <b>
                                        Maquinaría
                                    </b>
                                </h5>
                            </label>
                            <h5><b>{{ $assigmentTask->machinery->name }}</b></h5>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 mb-2">
                        <label for="comment" class="mb-2 pb-1 bg-espumados">
                            <h5>
                                <b>
                                    Prioridad
                                </b>
                            </h5>
                        </label>
                        <h5>Prioridad: {{ $assigmentTask->priority }}</h5>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label for="description_material" class="bg-espumados">
                                <h5>
                                    <b>
                                        Descripción del Material
                                    </b>
                                </h5>
                            </label>
                            <h5><b>{{ $assigmentTask->description_material }}</b></h5>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label for="order_pt" class="bg-espumados">
                                <h5>
                                    <b>
                                        N° de Producto terminado
                                    </b>
                                </h5>
                            </label>
                            <h5><b>{{ $assigmentTask->order_pt }}</b></h5>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
                        <div class="form-group">
                            <label for="client_name" class="bg-espumados">
                                <h5>
                                    <b>
                                        Nombre del Cliente
                                    </b>
                                </h5>
                            </label>
                            <h5><b>{{ $assigmentTask->client_name }}</b></h5>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label for="entry_date" class="bg-espumados">
                            <h5>
                                <b>
                                    Fecha de entrada
                                </b>
                            </h5>
                        </label>
                        <h5><b>{{ date('d-m-Y', strtotime($assigmentTask->entry_date)) }}</b></h5>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <label for="date_delivery" class="bg-espumados">
                            <h5>
                                <b>
                                    Fecha de disposición
                                </b>
                            </h5>
                        </label>
                        <h5><b>{{ date('d-m-Y', strtotime($assigmentTask->date_delivery)) }}</b></h5>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 mt-3">
                        <div class="form-group">
                            <label for="description" class="bg-espumados">
                                <h5>
                                    <b>
                                        Descripción de la tarea
                                    </b>
                                </h5>
                            </label>
                            <h5><b>{{ $assigmentTask->description }}</b></h5>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 mt-3">
                        <div class="form-group">
                            <label for="comment" class="bg-espumados">
                                <h5>
                                    <b>
                                        Comentarios a tener en cuenta
                                    </b>
                                </h5>
                            </label>
                            <h5><b>{{ ($assigmentTask->comment != null) ? $assigmentTask->comment : 'Sin comentarios adicionales' }}</b></h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">
                    Cerrar
                </button>
            </div>
        </div>
    </div>
</div>

resources/views/tasks/assignments/machinery.blade.php
<!-- Modal -->
<div class="modal fade" id="machinery" tabindex="-1" role="dialog" aria-labelledby="machineryTitle" aria-hidden="true">
    <div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title bg-espumados"
                    id="machineryLongTitle">
                    Identificador de maquinaria (Ventana informativa)
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body bv-modal">
                <div class="table-responsive">
                    <table class="table table-bordered table-sm table-striped table-condensed">
                        <thead class="bg-orange headerStatic">
                        <tr class="text-center">
                            <th class="tt-espumados">
                                Identificador para carga masiva
                            </th>
                            <th class="tt-espumados">
                                Nombre de la maquina
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr class="text-center" style="background: #FFF !important;">
                            @foreach($machineries as $machinery)
                                <td>{{ $machinery->id }}</td>
                                <td>{{ $machinery->name }}</td>
                            @endforeach
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <div class="btn-group">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        Cerrar
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>